### ISSUE TITLE
arm64 builds

### ISSUE THREAD

**Issue by miathedev** [paketo-buildpacks/jammy-base-stack#131]
## Describe the Enhancement

kNative users needs this stack to build/run their functions. If they use arm64 they cant build them, as this image is only published for amd64

## Possible Solution

https://github.com/paketo-buildpacks/jammy-base-stack/blob/main/.github/workflows/push-image.yml
```
jobs:
  push:
    name: Push
    runs-on: ubuntu-22.04
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-22.04]
        architecture: ['x64', 'arm64']
    steps:

    - name: Parse Event
```

## Motivation

Our k8s cluster runs on arm64.
